/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibreriaRouteImport } from './routes/libreria'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as SessioneRouteImport } from './routes/sessione'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibreriaRoute = LibreriaRouteImport.update({
  id: '/libreria',
  path: '/libreria',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const SessioneRoute = SessioneRouteImport.update({
  id: '/sessione',
  path: '/sessione',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/libreria': typeof LibreriaRoute
  '/network': typeof NetworkRoute
  '/sessione': typeof SessioneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/libreria': typeof LibreriaRoute
  '/network': typeof NetworkRoute
  '/sessione': typeof SessioneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/libreria': typeof LibreriaRoute
  '/network': typeof NetworkRoute
  '/sessione': typeof SessioneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/libreria' | '/network' | '/sessione'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/libreria' | '/network' | '/sessione'
  id: '__root__' | '/' | '/libreria' | '/network' | '/sessione'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibreriaRoute: typeof LibreriaRoute
  NetworkRoute: typeof NetworkRoute
  SessioneRoute: typeof SessioneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libreria': {
      id: '/libreria'
      path: '/libreria'
      fullPath: '/libreria'
      preLoaderRoute: typeof LibreriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessione': {
      id: '/sessione'
      path: '/sessione'
      fullPath: '/sessione'
      preLoaderRoute: typeof SessioneRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibreriaRoute: LibreriaRoute,
  NetworkRoute: NetworkRoute,
  SessioneRoute: SessioneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
